/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDataDisplay: typeof import('./src/components/TheDataDisplay.vue')['default']
    TheDataDisplayHeader: typeof import('./src/components/TheDataDisplayHeader.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
    TheToggleLayout: typeof import('./src/components/TheToggleLayout.vue')['default']
    TheTreeNode: typeof import('./src/components/VTreeView/TheTreeNode.vue')['default']
    TheViewLabelProgress: typeof import('./src/components/TheViewLabelProgress.vue')['default']
    TheViewLabelProgressButtons: typeof import('./src/components/TheViewLabelProgressButtons.vue')['default']
    TheViewSelectors: typeof import('./src/components/TheViewSelectors.vue')['default']
    TheViewTaxonomies: typeof import('./src/components/TheViewTaxonomies.vue')['default']
    TheViewTaxonomiesIndentedTree: typeof import('./src/components/TheViewTaxonomiesIndentedTree.vue')['default']
    TheViewTaxonomiesWithTreeView: typeof import('./src/components/TheViewTaxonomiesWithTreeView.vue')['default']
    TheWidgetAnnotationComparator: typeof import('./src/components/TheWidgetAnnotationComparator.vue')['default']
    TheWidgetSearch: typeof import('./src/components/TheWidgetSearch.vue')['default']
    VBarColumns: typeof import('./src/components/VIndentedTree/VBarColumns.vue')['default']
    VDialog: typeof import('./src/components/VDialog.vue')['default']
    VIndentedTree: typeof import('./src/components/VIndentedTree/VIndentedTree.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VMessage: typeof import('./src/components/VMessage.vue')['default']
    VMessages: typeof import('./src/components/VMessages.vue')['default']
    VSelector: typeof import('./src/components/VSelector.vue')['default']
    VTextColumns: typeof import('./src/components/VIndentedTree/VTextColumns.vue')['default']
    VTreeView: typeof import('./src/components/VTreeView/VTreeView.vue')['default']
  }
}
