/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDataDisplay: typeof import('./src/components/TheDataDisplay.vue')['default']
    TheDataDisplayHeader: typeof import('./src/components/TheDataDisplayHeader.vue')['default']
    TheDialogLogin: typeof import('./src/components/TheDialogLogin.vue')['default']
    TheNavBar: typeof import('./src/components/TheNavBar.vue')['default']
    TheToggleLayout: typeof import('./src/components/TheToggleLayout.vue')['default']
    TheTreeNode: typeof import('./src/components/VTreeView/TheTreeNode.vue')['default']
    TheViewLabelProgress: typeof import('./src/components/TheViewLabelProgress.vue')['default']
    TheViewLabelProgressButtons: typeof import('./src/components/TheViewLabelProgressButtons.vue')['default']
    TheViewSelectors: typeof import('./src/components/TheViewSelectors.vue')['default']
    TheViewTaxonomy: typeof import('./src/components/TheViewTaxonomy.vue')['default']
    TheWidgetClassification: typeof import('./src/components/TheWidgetClassification.vue')['default']
    TheWidgetLoad: typeof import('./src/components/TheWidgetLoad.vue')['default']
    TheWidgetSearch: typeof import('./src/components/TheWidgetSearch.vue')['default']
    TheWidgetTaxonomization: typeof import('./src/components/TheWidgetTaxonomization.vue')['default']
    VDialog: typeof import('./src/components/VDialog.vue')['default']
    VInput: typeof import('./src/components/VTreeView/VInput.vue')['default']
    VMessage: typeof import('./src/components/VMessage.vue')['default']
    VMessages: typeof import('./src/components/VMessages.vue')['default']
    VSelector: typeof import('./src/components/VSelector.vue')['default']
    VTreeView: typeof import('./src/components/VTreeView/VTreeView.vue')['default']
  }
}
